name: Automatic Stable Release

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  issues: write
  security-events: read

jobs:
  release:
    uses: ./.github/workflows/managed-automatic-release.yml
